Add functionality to list all the storage classes under persistent volumes section
openebs/scope pull request #29
Opened 2018-03-19 12:39 UTC by sagarkrsd

Signed-off-by: sagarkrsd <sagar.kumar@openebs.io>

**What this PR does / why we need it**:
- This PR will add the functionality to list all the storage classes under persistent volumes (sub-topology of PODS) alongwith PVs and PVCs.
- Storage classes will be displayed in triangle shape

**Which issue this PR fixes** 
 - fixes : #23

2018-03-19 12:50 UTC, qiell requested changes

2018-03-19 12:50 UTC, Akash4927 commented on probe/kubernetes/storageclass.go
> +type person struct {
What is type person struct here?

2018-03-19 12:51 UTC, sagarkrsd commented on probe/kubernetes/storageclass.go
> +type person struct {
Ohhh... My bad !!!
Thanks !!

2018-03-19 12:57 UTC, qiell approved these changes

2018-03-20 06:21 UTC, qiell requested changes

2018-03-20 06:21 UTC, Akash4927 commented on probe/kubernetes/client.go
> +	storage_v1 "k8s.io/api/storage/v1"
Will you please replace `storage_v1` with `storagev1` because  I think we should use the same methodology of Weave Scope to declare variables.

2018-03-20 10:32 UTC, satyamz approved these changes
lgtm @sagarkrsd  
Please make changes requested by @Akash4927

2018-03-20 11:17 UTC, sagarkrsd commented
@satyamz @Akash4927  Done with changes !

2018-03-20 11:20 UTC, qiell approved these changes
lgtm

2018-03-20 12:32 UTC, satyamz commented
Hi @sagarkrsd & @Akash4927 
Build is failing because reporter test has failed. Can you look into it? 
Here's what happened:

```


# github.com/weaveworks/scope/probe/kubernetes_test

probe/kubernetes/reporter_test.go:197:48: cannot use newMockClient() (type *mockClient) as type kubernetes.Client in argument to kubernetes.NewReporter:

	*mockClient does not implement kubernetes.Client (missing WalkPersistentVolume method)

probe/kubernetes/reporter_test.go:258:50: cannot use newMockClient() (type *mockClient) as type kubernetes.Client in argument to kubernetes.NewReporter:

	*mockClient does not implement kubernetes.Client (missing WalkPersistentVolume method)

probe/kubernetes/reporter_test.go:287:36: cannot use client (type *mockClient) as type kubernetes.Client in argument to kubernetes.NewReporter:

	*mockClient does not implement kubernetes.Client (missing WalkPersistentVolume method)

FAIL	github.com/weaveworks/scope/probe/kubernetes [build failed]
```
 Here's how to fix:
Implement method `WalkPersistentVolume` in reporter_test.go and attach it to  ` *mockClient` 
Also, make sure same for PVC, SC etc.

2018-03-21 07:17 UTC, merged