Add config to integrate with circle ci
openebs/scope pull request #89
Opened 2018-06-28 12:37 UTC by Pradeepkumarbk

-  Set up circle CI , so whenever a PR is raised CI starts up and builds docker image .
-   when PR is merged the docker image gets pushed into docker hub.
- If PR is merged against `staging`branch - image with `tag` will be pushed to docker hub repo(i.e openebs/scope) .
- If PR is merged against `master`branch - image with `latest` will be pushed to docker hub repo(i.e openebs/scope).

Signed-off-by: Pradeepkumarbk <pradeepkumar.bk96@gmail.com>

2018-06-28 14:40 UTC, satyamz requested changes

2018-06-28 14:40 UTC, satyamz commented on circle.yml
> +      - docker push openebs/scope:latest
Please do not push these to the `openebs/scope:lastest` change it to `openebs/scope:ci`

2018-06-28 14:40 UTC, satyamz commented on docker/Dockerfile.scope
> +FROM openebs/cloud-agent
I think we also don't need this change. Instead let it build and tag the final image with openebs prefix

2018-06-28 14:40 UTC, satyamz commented on extras/Makefile
> +		openebs/scope-backend-build -C extras $@
same comment apply here too

2018-06-28 15:48 UTC, qiell requested changes
@Pradeepkumarbk I agree with @satyamz 
Let's build the image using weaveworks and later we can tag it and push it.

2018-06-28 15:48 UTC, Akash4927 commented on circle.yml
> -    - cd $SRCDIR; make RM= lint:
why is this removed? I think we should check linting errors before creating a build.

2018-06-28 15:48 UTC, Akash4927 commented on circle.yml
> -    - cd $SRCDIR; make RM= client-lint static:
same here.

2018-06-29 06:19 UTC, satyamz approved these changes
lgtm @Pradeepkumarbk Can you change the commit message? Its not good.

2018-06-29 06:24 UTC, qiell approved these changes
lgtm

2018-06-29 07:40 UTC, merged